site_name: EasyAdmin
site_description: EasyAdmin Documentation

repo_url: "https://github.com/Blumlaut/EasyAdmin"
edit_uri: "https://github.com/Blumlaut/EasyAdmin-docs/edit/main/docs/"

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - toc:
      permalink: True


plugins:
  - search
  - git-revision-date

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - search.highlight
    - toc.integrate


extra_css:
  - stylesheets/extra.css

nav:
    - "Index": 'index.md'
    - "Installation":
        -'install-welcome.md'
        - "Install cPanel": 'install/cpanel-welcome.md'

    - 'install.md'
    - 'Configuration':
        - 'config.md'
        - 'permissions.md'
    - 'Guides':
        - "Adding Admins": 'install/#adding-an-admin'
        - 'discord-screenshots.md'd'
        - 'backups.md'
        - 'updating.md'
    - 'Troubleshooting':
      - 'troubleshooting.md'
      - 'supportfile.md'
    - 'Developer Reference':
        - 'plugins.md'
        - 'translating.md'
  
