site_name: OpenCAD
site_description: OpenCAD Documentation

repo_url: "https://github.com/Blumlaut/EasyAdmin"
edit_uri: "https://github.com/Blumlaut/EasyAdmin-docs/edit/main/docs/"

markdown_extensions:
    - pymdownx.highlight:
        linenums: true
    - pymdownx.superfences
    - toc:
        permalink: True


plugins:
    - search
    - git-revision-date

theme:
    name: material
    logo: assets/logo.png
    favicon: assets/favicon.png
    palette:
    - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: blue
    accent: blue
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.top
        - search.highlight
        - toc.integrate

extra_css:
    - stylesheets/extra.css

nav:
    - "Index": 'index.md'
    - "Installation":
        - "Welcome": 'install/install-welcome.md'
        - 'install/cpanel-welcome.md'
        - 'install/directadmin-welcome.md'
        - 'install/autoinstaller.md'
        - 'install/manual-install.md'
    - 'Support':
        - 'support/support-welcome.md'
    - 'Developer Reference':
        - 'developer/plugins.md'
        - 'developer/translating.md'