site_name: OpenCAD
site_description: OpenCAD Documentation

repo_url: "https://github.com/OpenCAD-app/OpenCAD-docs"
edit_uri: "https://github.com/OpenCAD-app/OpenCAD-docs/docs/"

markdown_extensions:
    - pymdownx.highlight:
        linenums: true
    - pymdownx.superfences


plugins:
    - search
    - git-revision-date

theme:
    name: material
    nav_style: dark
    logo: assets/logo.png
    favicon: assets/logo.png
    scheme: slate
    palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    features:
        - navigation.tabs
        - navigation.tracking
        - navigation.top
        - search.highlight
        - toc.integrate

extra_css:
    - stylesheets/extra.css

extra:
  version:
    provider: mike

nav:
    - "Home": 'index.md'
    - "Installation":
        - "Welcome": 'install/install-welcome.md'
        - 'install/cpanel-welcome.md'
        - 'install/directadmin-welcome.md'
        - 'install/iis-install.md'
        - 'install/dev-xampp-install.md'
        - 'install/autoinstaller.md'
    - "Administrator Guides":
        - "Welcome": 'admin/admin-welcome.md'
        - "User Administration": 'admin/user-admin/user-admin-welcome.md'
        - "Civilian Administration": 'admin/civ-admin/civ-admin-welcome.md'
        - "Data Type Management": 'admin/data-type-mgmt/data-type-mgmt-welcome.md'
    - "User Guides":
        - "Welcome": 'user/user-welcome.md'
    - 'Support':
        - 'support/support-welcome.md'
    - 'Developer Reference':
        - 'developer/plugins.md'
        - 'developer/translating.md'